# Generated by Django 4.0.5 on 2022-06-15 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resumo', models.CharField(max_length=2000)),
                ('resume', models.CharField(max_length=2000)),
                ('autor', models.CharField(max_length=100)),
                ('titulo', models.CharField(max_length=200)),
                ('palavraschave', models.CharField(max_length=100)),
                ('direitosdeuso', models.CharField(max_length=100)),
                ('local', models.CharField(max_length=100)),
                ('datapubli', models.DateField()),
                ('Doe', models.CharField(max_length=50)),
                ('Revista', models.CharField(max_length=50)),
            ],
        ),
    ]
